CampaignManager.Web/Controllers/CampaignsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CampaignManager.Persistence.Models;
using CampaignManager.Persistence.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using static System.Net.Mime.MediaTypeNames;
using CampaignManager.DTO;
using Microsoft.CodeAnalysis.CSharp.Scripting;
using Microsoft.CodeAnalysis.Scripting;
using System.Text.Json;

namespace CampaignManager.Web.Controllers
{
    public enum SortOrder { NAME_DESC, NAME_ASC, CREATED_DESC, CREATED_ASC, EDITED_DECS, EDITED_ASC }

    [Authorize]
    public class CampaignsController : Controller
    {
        private readonly ICampaignManagerService _service;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<CampaignsController> _logger;

        [TempData]
        public string[] SuccessNotifications { get; set; } = Array.Empty<string>();

        [TempData]
        public string[] ErrorNotifications { get; set; } = Array.Empty<string>();


        public CampaignsController(ICampaignManagerService service, UserManager<ApplicationUser> userManager, ILogger<CampaignsController> logger)
        {
            _service = service;
            _userManager = userManager;
            _logger = logger;
        }

        public async Task<IActionResult?> DisplayImage(Guid id)
        {
            var campaign = await _service.GetCampaignById(id);
            if (campaign != null && campaign.Image != null)
            {
                return File(campaign.Image, "image/png");
            }
            return null;
        }

        #region Create Methods

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,GameTime")] Campaign campaign, IFormFile? image)
        {
            if (image != null && image.Length > 0)
            {
                using (var stream = new MemoryStream())
                {
                    image.CopyTo(stream);
                    campaign.Image = stream.ToArray();
                }
            }

            if (!ModelState.IsValid)
            {
                return View(campaign);
            }

            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                TempData["ErrorMessage"] = "You need to be logged in to create a campaign.";
                return RedirectToAction("Login", "Account");
            }

            bool existWithName = await _service.IsReservedCampaignNameForUser(campaign.Name, userId);
            if (existWithName)
            {
                ModelState.AddModelError("Name", "Campaign with this name already exists.");
                return View(campaign);
            }

            campaign.OwnerId = userId;
            campaign.Created = DateTime.Now;
            campaign.Edited = DateTime.Now;

            // Use transactions to ensure that both the campaign and the game master are added
            using (var transaction = await _service.BeginTransactionAsync())
            {
                try
                {
                    bool campaignAdded = await _service.AddCampaign(campaign);
                    if (campaignAdded)
                    {
                        // Add the owner as a game master
                        var GM = new CampaignParticipant
                        {
                            ApplicationUserId = userId,
                            CampaignId = campaign.Id, // Ensure CampaignId is set correctly
                            Role = Role.GameMaster, // Use the correct role
                        };

                        bool participantAdded = await _service.AddCampaignParticipant(GM);
                        if (participantAdded)
                        {
                            await transaction.CommitAsync();
                            return RedirectToAction(nameof(IndexOwned));
                        }
                        else
                        {
                            await transaction.RollbackAsync();
                            ModelState.AddModelError("", "There was an error during saving the participant");
                        }
                    }
                    else
                    {
                        await transaction.RollbackAsync();
                        ModelState.AddModelError("", "There was an error during saving the campaign");
                    }
                }
                catch (Exception ex)
                {
                    await transaction.RollbackAsync();
                    _logger.LogError(ex, "Exception during transaction");
                    ModelState.AddModelError("", "There was an error during saving");
                }
            }


            return View(campaign);


        }

        [HttpGet]
        public IActionResult LoadCampaign()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LoadCampaign(IFormFile jsonFile)
        {
            if (jsonFile == null || jsonFile.Length == 0)
            {
                TempData["ErrorMessage"] = "Please select a valid JSON file.";
                return View();
            }

            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                TempData["ErrorMessage"] = "You need to be logged in to load a campaign.";
                return RedirectToAction("Login", "Account");
            }

            string filePath = Path.Combine(Path.GetTempPath(), jsonFile.FileName);


            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await jsonFile.CopyToAsync(stream);
            }

            var campaign = await _service.LoadCampaignFromFile(filePath);
            if (campaign == null)
            {
                TempData["ErrorMessage"] = "Failed to load campaign from the JSON file.";
                return View();
            }

            bool existWithName = await _service.IsReservedCampaignNameForUser(campaign.Name, userId);
            if (existWithName)
            {
                TempData["ErrorMessage"] = "Campaign with this name already exists.";
                return View();
            }

            using (var transaction = await _service.BeginTransactionAsync())
            {
                try
                {
                    campaign.OwnerId = userId;

                    bool campaignAdded = await _service.AddCampaign(campaign);
                    if (!campaignAdded)
                    {
                        await transaction.RollbackAsync();
                        TempData["ErrorMessage"] = "Failed to add the loaded campaign.";
                        return View();
                    }

                    var campaignParticipant = new CampaignParticipant
                    {
                        ApplicationUserId = userId,
                        CampaignId = campaign.Id,
                        Role = Role.GameMaster
                    };

                    bool participantAdded = await _service.AddCampaignParticipant(campaignParticipant);
                    if (!participantAdded)
                    {
                        await transaction.RollbackAsync();
                        TempData["ErrorMessage"] = "Failed to add the loaded campaign.";
                        return View();
                    }

                    await transaction.CommitAsync();
                    TempData["SuccessMessage"] = "Campaign loaded successfully.";
                    return RedirectToAction(nameof(IndexOwned));
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Error adding campaign with ownership");
                    await transaction.RollbackAsync();
                    TempData["ErrorMessage"] = "Failed to add the loaded campaign.";
                    return View();
                }
            }
        }

        /*
        [HttpGet]
        public async Task<IActionResult> AddNoteAdmin(int? campaignId)
        {
            if (campaignId == null)
            {
                return NotFound();
            }

            var campaign = await _service.GetCampaignById(campaignId.Value);
            if (campaign == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                TempData["ErrorMessage"] = "You need to be logged in to add note admins to this campaign.";
                return RedirectToAction("Login", "Account");
            }

            if (campaign.OwnerId != user.Id)
            {
                TempData["ErrorMessage"] = "You do not have permission to add note admins to this campaign.";
                return RedirectToAction("Details", new { id = campaignId });
            }

            var participants = await _service.GetParticipantsForCampaign((int)campaignId);
            var noteAdmins = await _service.GetNoteAdminsForCampaign((int)campaignId);

            var filteredParticipants = participants
                .Where(p => !noteAdmins.Any(na => na.ApplicationUserId == p.ApplicationUserId))
                .ToList();

            var model = new ManageNoteAdminViewModel
            {
                CampaignId = (int)campaignId,
                Participants = new SelectList(filteredParticipants, "ApplicationUserId", "ApplicationUser.UserName")
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

CampaignManager.Web/Views/Invitations/Create.cshtml
@model CampaignManager.Persistence.Models.CreateInvitationViewModel

@{
    ViewData["Title"] = "Send Invitation";

    Func<Role, String> RoleConverter = role =>
    {
        switch (role)
        {
            case Role.GameMaster: return "Gamemaster";
            case Role.Player: return "Player";
            case Role.PlayerAndGameMaster: return "Player and Gamemaster";
            default: return "?";
        }
    };
}


<h1>Send Invitation</h1>

<div class="details-view">
<h4>Invitation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label">Role</label>
                <select asp-for="Role" class="form-control">
                    @foreach (var role in Model.Roles)
                    {
                        <option value="@role.Value">@RoleConverter((Role)Enum.Parse(typeof(Role), role.Value))</option>
                    }
                </select>
            </div>
            <input type="hidden" asp-for="CampaignId" />
            <div class="form-group">
                <input type="submit" value="Send" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</div>

<p> </p>

<div>
    <a asp-controller="Campaigns" asp-action="Details" asp-route-id="@Model.CampaignId">Back to Campaign</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CampaignManager.Web/Views/Invitations/Index.cshtml
@model IEnumerable<CampaignManager.Persistence.Models.Invitation>

@{
    ViewData["Title"] = "Invitations";
    var errorMessage = TempData["ErrorMessage"] as string;
}

@if (!string.IsNullOrEmpty(errorMessage))
{
    <div class="alert alert-danger">
        @errorMessage
    </div>
}

@{
    Func<Role, String> RoleConverter = role =>
    {

        switch (role)
        {
            case Role.GameMaster: return "Gamemaster";
            case Role.Player: return "Player";
            case Role.PlayerAndGameMaster: return "Player And Gamemaster";
            default: return "?";
        }
    };
}

<h1>Invitations</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Campaign Image
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Campaign.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th>Accept</th>
            <th>Reject</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (item.Campaign.Image != null)
                    {
                        <img src="@Url.Action("DisplayImage", "Campaigns", new { id = item.CampaignId })" class="item" />
                    }
                    else
                    {
                        <text>No image</text>
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Campaign.Name)
                </td>
                <td>
                    @RoleConverter(item.Role)
                </td>
                <td>
                    <a asp-action="Accept" asp-route-id="@item.Id" class="btn btn-success">Accept</a>
                </td>
                <td>
                    <a asp-action="Reject" asp-route-id="@item.Id" class="btn btn-danger">Reject</a>
                </td>
            </tr>
        }
    </tbody>
</table>