CampaignManager.Web/Controllers/NoteTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CampaignManager.Persistence.Models;
using CampaignManager.Persistence.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using static System.Net.Mime.MediaTypeNames;

namespace CampaignManager.Web.Controllers
{
    public class NoteTypesController : Controller
    {
        private readonly ICampaignManagerService _service;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<CampaignsController> _logger;

        public NoteTypesController(ICampaignManagerService service, UserManager<ApplicationUser> userManager, ILogger<CampaignsController> logger)
        {
            _service = service;
            _userManager = userManager;
            _logger = logger;
        }

        // GET: Generators/Create
        [HttpGet]
        public IActionResult Create()
        {
            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                TempData["ErrorMessage"] = "You need to be logged in to create a note type.";
                return RedirectToAction("Login", "Account");
            }

            return View();
        }

        // POST: NoteTypes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,PlayerTemplateId,GameMasterTemplateId")] NoteType noteType)
        {
            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                TempData["ErrorMessage"] = "You need to be logged in to create a note type.";
                return RedirectToAction("Login", "Account");
            }
            
            if (noteType.PlayerTemplateId == null)
            {
                ModelState.AddModelError("PlayerTemplateId", "Player Template ID is required.");
            }
            if(noteType.GameMasterTemplateId == null)
            {
                ModelState.AddModelError("GameMasterTemplateId", "Game Master Template ID is required.");
            }

            if (ModelState.IsValid)
            {
                if (!await IsValidTemplateId(noteType.PlayerTemplateId))
                {
                    ModelState.AddModelError("PlayerTemplateId", "Invalid Player Template ID.");
                }
                if (!await IsValidTemplateId(noteType.GameMasterTemplateId))
                {
                    ModelState.AddModelError("GameMasterTemplateId", "Invalid Game Master Template ID.");
                }

                noteType.Id = Guid.NewGuid();
                noteType.OwnerId = userId;
                var result = await _service.AddNoteType(noteType);
                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", "Unable to create note type. Please try again.");
            }
            return View(noteType);
        }

        // GET: NoteTypes
        [HttpGet]
        public async Task<IActionResult> Index(int page = 1, int pageSize = 10)
        {
            var (noteTypes, totalCount) = await _service.GetPaginatedNoteTypes(page, pageSize);
            var totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);

            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = totalPages;

            return View(noteTypes);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                TempData["ErrorMessage"] = "You need to be logged in to view this note type.";
                return RedirectToAction("Login", "Account");
            }

            var noteType = await _service.GetNoteTypeById((Guid)id);
            if (noteType == null)
            {
                return NotFound();
            }

            return View(noteType);
        }


        // GET: NoteTypes/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                TempData["ErrorMessage"] = "You need to be logged in to edit this note type.";
                return RedirectToAction("Login", "Account");
            }

            var noteType = await _service.GetNoteTypeById((Guid)id);
            if (noteType == null)
            {
                return NotFound();
            }

            if (noteType.OwnerId != userId)
            {
                TempData["ErrorMessage"] = "You do not have permission to edit this note type.";
                return RedirectToAction(nameof(Index));
            }

            return View(noteType);
        }

        // POST: NoteType/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid? id, [Bind("Id,Name,PlayerTemplateId,GameMasterTemplateId")] NoteType noteType)
        {
            if (id == null || id != noteType.Id)
            {
                return NotFound();
            }

            if (!await IsValidTemplateId(noteType.PlayerTemplateId))
            {
                ModelState.AddModelError("PlayerTemplateId", "Invalid Player Template ID.");
            }
            if (!await IsValidTemplateId(noteType.GameMasterTemplateId))
            {
                ModelState.AddModelError("GameMasterTemplateId", "Invalid Game Master Template ID.");
            }

            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                if (userId == null)
                {
                    TempData["ErrorMessage"] = "You need to be logged in to edit this note type.";
                    return RedirectToAction("Login", "Account");
                }

                var existingNoteType = await _service.GetNoteTypeById((Guid)id);
                if (existingNoteType == null)
                {
                    return NotFound();
                }

                if (existingNoteType.OwnerId != userId)
                {
                    TempData["ErrorMessage"] = "You do not have permission to edit this note type";
                    return RedirectToAction(nameof(Index));
                }

                existingNoteType.Name = noteType.Name;
                existingNoteType.PlayerTemplateId = noteType.PlayerTemplateId;
                existingNoteType.GameMasterTemplateId = noteType.GameMasterTemplateId;
                //existingNoteType.PlayerViewTemplateId = noteType.PlayerViewTemplateId;
                //existingNoteType.GameMasterViewTemplateId = noteType.GameMasterViewTemplateId;
                //existingNoteType.PlayerEditTemplateId = noteType.PlayerEditTemplateId;
                //existingNoteType.GameMasterEditTemplateId = noteType.GameMasterEditTemplateId;


                var result = await _service.UpdateNoteType(existingNoteType);
                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "There was an error during saving");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(noteType);
        }

        // GET: NoteType/Delete/5
                [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                TempData["ErrorMessage"] = "You need to be logged in to delete this note type.";
                return RedirectToAction("Login", "Account");
            }

            var noteType = await _service.GetNoteTypeById((Guid)id);
            if (noteType == null)
            {
                return NotFound();
            }

            if (noteType.OwnerId != userId)
            {
                TempData["ErrorMessage"] = "You do not have permission to delete this not type.";
                return RedirectToAction(nameof(Index));
            }

            return View(noteType);
        }

        // POST: NoteType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                TempData["ErrorMessage"] = "You need to be logged in to delete this note type.";
                return RedirectToAction("Login", "Account");
            }

            var noteType = await _service.GetNoteTypeById((Guid)id);
            if (noteType == null)
            {
                return NotFound();
            }

            if (noteType.OwnerId != userId)
            {
                TempData["ErrorMessage"] = "You do not have permission to delete this note type.";
                return RedirectToAction(nameof(Index));
            }

            var result = await _service.DeleteNoteTypeById((Guid)id);
            if (!result)
            {
                TempData["ErrorMessage"] = "Unable to delete note type. Please ensure the note type is not used in campaigns";

CampaignManager.Web/Views/NoteTypes/AddGenerator.cshtml
@model ManageNoteTypeGeneratorViewModel

@{
    ViewData["Title"] = "Add Generator";
}

<h1>Add Generator</h1>

<div class="details-view">
<form asp-action="AddGenerator">
    <div class="form-group">
        <label asp-for="GeneratorId" class="control-label">Generator ID</label>
        <input asp-for="GeneratorId" class="form-control" />
        <span asp-validation-for="GeneratorId" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="NoteTypeId" />
    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-primary" />
    </div>
</form>
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model.NoteTypeId" class="btn btn-primary">Back to NoteType</a>
</div>

CampaignManager.Web/Views/NoteTypes/Create.cshtml
@model CampaignManager.Persistence.Models.NoteType

@{
    ViewData["Title"] = "Create Note Type";
}

<h1>Create NoteType</h1>

<div class="details-view">
<h4>NoteType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerTemplateId" class="control-label"></label>
                <input asp-for="PlayerTemplateId" class="form-control" />
                <span asp-validation-for="PlayerTemplateId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GameMasterTemplateId" class="control-label"></label>
                <input asp-for="GameMasterTemplateId" class="form-control" />
                <span asp-validation-for="GameMasterTemplateId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</div>

<p></p>

<div>
    <a class="btn btn-primary" asp-action="Index">Back to Index</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CampaignManager.Web/Views/NoteTypes/Delete.cshtml
@model CampaignManager.Persistence.Models.NoteType

@{
    ViewData["Title"] = "Delete NoteType";
    var errorMessage = TempData["ErrorMessage"] as string;
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

<h1>Delete NoteType</h1>

<h3>Are you sure you want to delete this note type?</h3>
<div class="details-view">
    <h4>NoteType</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        @Html.AntiForgeryToken()
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="NoteTypes" asp-action="Index" class="btn btn-secondary">Cancel</a>
    </form>
</div>

CampaignManager.Web/Views/NoteTypes/Details.cshtml
@using System.Security.Claims;
@model CampaignManager.Persistence.Models.NoteType

@{
    ViewData["Title"] = "Note Type Details";
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var successMessage = TempData["SuccessMessage"] as string;
    var errorMessage = TempData["ErrorMessage"] as string;
}

@if(!string.IsNullOrEmpty(successMessage))
{
    <div class="alert alert-success">
        @successMessage
    </div>
}


@if (!string.IsNullOrEmpty(errorMessage))
{
    <div class="alert alert-danger">
        @errorMessage
    </div>
}

<h1>NoteType Details</h1>

<div class="details-view">
<dl class="row">
    <dt class="col-sm-2">
        Name
    </dt>
    <dd class="col-sm-10">
        @Model.Name
    </dd>

    <dt class="col-sm-2">
        Owner
    </dt>
    <dd class="col-sm-10">
        @Model.Owner?.UserName
    </dd>

    <dt class="col-sm-2">
        Player Template Id
    </dt>
    <dd class="col-sm-10">
        @Model.PlayerTemplateId
    </dd>

    <dt class="col-sm-2">
        Gamemaster Template Id
    </dt>
    <dd class="col-sm-10">
        @Model.GameMasterTemplateId
    </dd>
</dl>
</div>

<h2>Generators</h2>

@if (Model.Generators == null || !Model.Generators.Any())
{
    <p>No generators yet</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Owner</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Generators)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Owner?.UserName</td>
                </tr>
            }
        </tbody>
    </table>
}

@if (Model.Owner?.Id == userId)
{
    <p>
        <a asp-action="AddGenerator" asp-route-noteTypeId="@Model.Id" class="btn btn-primary">Add Generator</a> |
        <a asp-action="RemoveGenerator" asp-route-noteTypeId="@Model.Id" class="btn btn-danger">Remove Generator</a>
    </p>
}

<p>
    <a class="btn btn-primary" asp-action="Index" class="btn btn-primary">Back to Index</a>
</p>

CampaignManager.Web/Views/NoteTypes/Edit.cshtml
@model CampaignManager.Persistence.Models.NoteType

@{
    ViewData["Title"] = "Edit NoteType";
}

<h1>Edit NoteType</h1>

<div class="details-view">
<h4>Note Type</h4>
<hr />
<div class="row">
    <div class="col-md-4">

        <form asp-action="Edit">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerTemplateId" class="control-label"></label>
                <input asp-for="PlayerTemplateId" class="form-control" />
                <span asp-validation-for="PlayerTemplateId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GameMasterTemplateId" class="control-label"></label>
                <input asp-for="GameMasterTemplateId" class="form-control" />
                <span asp-validation-for="GameMasterTemplateId" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>

    </div>
</div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Back to Index</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CampaignManager.Web/Views/NoteTypes/Index.cshtml
@using System.Security.Claims
@model List<CampaignManager.Persistence.Models.NoteType>

@{
    ViewData["Title"] = "Note Types";
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var successMessage = TempData["SuccessMessage"] as string;
    var errorMessage = TempData["ErrorMessage"] as string;
}

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

<h1>NoteTypes</h1>


<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Owner</th>
            <th>Player Template Id</th>
            <th>Gamemaster Template Id</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Owner?.UserName</td>
                <td>@(item.PlayerTemplateId.HasValue ? item.PlayerTemplateId.ToString() : "No template set")</td>
                <td>@(item.GameMasterTemplateId.HasValue ? item.GameMasterTemplateId.ToString() : "No template set")</td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a>
                    @if (userId == item.OwnerId)
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Edit</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                    }
                    
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="pagination">
    <ul class="pagination">
        @if (ViewBag.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link" asp-action="Index" asp-route-page="@(ViewBag.CurrentPage - 1)">Previous</a>
            </li>
        }
        @for (int i = 1; i <= ViewBag.TotalPages; i++)
        {
            <li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
                <a class="page-link" asp-action="Index" asp-route-page="@i">@i</a>
            </li>
        }
        @if (ViewBag.CurrentPage < ViewBag.TotalPages)
        {
            <li class="page-item">
                <a class="page-link" asp-action="Index" asp-route-page="@(ViewBag.CurrentPage + 1)">Next</a>
            </li>
        }
    </ul>
</div>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New Note Type</a>
</p>

CampaignManager.Web/Views/NoteTypes/RemoveGenerator.cshtml
@model CampaignManager.Persistence.Models.ManageNoteTypeGeneratorViewModel

@{
    ViewData["Title"] = "Remove Generator";
}

<h1>Remove Generator</h1>

<div class="details-view">
<form asp-action="RemoveGenerator">
    <div class="form-group">
        <label asp-for="GeneratorId" class="control-label">Generator ID</label>
        <input asp-for="GeneratorId" class="form-control" />
        <span asp-validation-for="GeneratorId" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="NoteTypeId" />
    <div class="form-group">
        <input type="submit" value="Remove" class="btn btn-danger" />
    </div>
</form>
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model.NoteTypeId" class="btn btn-primary">Back to Details</a>
</div>